Cria controller com busca e inserção de pessoa
flavioh-assis/java-rest-api pull request #1
Opened 2022-11-22 02:03 UTC by flavioh-assis

2022-11-22 21:27 UTC, M4urici0GM requested changes
Acho que ta lega, tem umas coisas que daria pra melhorar
como o uso do lombok e tals, escrever testes (principalmente de integração no seu caso)

mas já é um grande começo 👍🏻

2022-11-22 21:27 UTC, M4urici0GM commented on src/main/java/com/flavio/javarestapi/controller/PersonController.java
> +
esse espaço em branco aqui 👀

2022-11-22 21:27 UTC, M4urici0GM commented on src/main/java/com/flavio/javarestapi/controller/PersonController.java
> +        return repository.findById(id)
não sei se é interessante chamar o repository assim direto no controller
tenta separar isso num serviço, vai facilitar testes e desacoplar controller <-> repository

2022-11-22 21:27 UTC, M4urici0GM commented on src/main/java/com/flavio/javarestapi/model/Address.java
> +    public Address(String street, String city, String state, int zipCode) {
pq n usar lombok aqui? 👀

2022-11-22 21:27 UTC, M4urici0GM commented on src/main/java/com/flavio/javarestapi/model/Address.java
> +    public String getStreet() {
mesma coisa aqui 👀

2022-11-22 21:27 UTC, M4urici0GM commented on src/main/java/com/flavio/javarestapi/model/Person.java
> +    public Person() {
construtor vazio? acho q n precisa

2022-11-23 01:44 UTC, flavioh-assis commented
eu segui esse [video](https://www.youtube.com/watch?v=0HKAqjiZveE). A intencão era só fazer o básico pra melhorar com praticantes ativos hehe. thank u very much

2022-11-24 13:27 UTC, flavioh-assis commented on src/main/java/com/flavio/javarestapi/model/Address.java
> +    public String getStreet() {
Deletei esse model q ñ tava sendo utilizado

2022-11-24 14:10 UTC, flavioh-assis commented on src/main/java/com/flavio/javarestapi/model/Address.java
> +    public Address(String street, String city, String state, int zipCode) {
Removi esse arquivo, mas usei o lombok em Person

2022-11-29 17:39 UTC, M4urici0GM approved these changes

2023-10-13 14:01 UTC, merged